### PR TITLE
Removed the need to manage two tables for favorites. Now at least we can display them both in one UI

### PR DESCRIPTION
**Pull request by danielgalasko**
I was really unhappy with #4 in that we had two Realm tables of elements. This means we could not display a single list displaying favorites and normal together.

This PR simplifies our model nicely by just moving to one property on element for favoriting

### CODE REVIEW

**Comment by danielgalasko** [comment]
@tenfef this is definitely more inline with what we need

**Comment by danielgalasko** [comment]
@tenfef this is more inline with what I was saying. Thoughts? I think this is much simpler and easier to digest

**Comment by tenfef** [comment]
Yip thats much simpler, i like it.

**Comment by danielgalasko** [comment]
Need your approval then @tenfef making sure every PR needs a review before being merged :)

**Review by tenfef — APPROVED** [review]
All good 👍

**Pull request merged**
